version: "3.4"

services:
  database:
    container_name: database
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file: ./.env.database
    volumes:
      - ./dockerdata/postgres:/var/lib/postgresql/data

  database-dashboard:
    container_name: database-dashboard
    image: adminer:latest
    ports:
      - 8080:8080
